#page title
page_title: Catima - The Libre Card Wallet # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
#ios_app_id: 1234793120 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
#ios_app_country: us # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/store/apps/details?id=me.hackerchick.catima # Enter Google Play Store URL.
fdroid_link: https://f-droid.org/en/packages/me.hackerchick.catima/
#presskit_download_link: https://emilbaehr.com # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Catima # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: A Loyalty Card & Ticket Manager for Android

enable_smart_app_banner: false # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: The Catima Community
your_link: https://github.com/CatimaLoyalty/Android/graphs/contributors
email_address: catima.g9ex3@hackerchick.me
facebook_username:
instagram_username:
twitter_username:
github_username: CatimaLoyalty
youtube_username:

# Accolade list
accolades:
- text: "[Catima] doesn't require internet access, shows no ads and doesn't share any data. That makes it the perfect solution."
  publisher:
    logo: ct.svg
    name: "C't"
  source: "https://youtu.be/0CjAPZ_IWVA?t=1537"

# Feature List
# Edit, add or remove features to be presented.
features:
- title: Truly Free
  description: No ads, no tracking, no nonsense. <a href="https://github.com/TheLastProject/Catima">Open Source</a> because we have nothing to hide.
  fontawesome_icon_name: star

- title: Easy As 1-2-3
  description: Just scan and go with the built-in barcode scanner.
  fontawesome_icon_name: magic

- title: Add Any Store
  description: Supports more than 10 different barcode types.
  fontawesome_icon_name: store

- title: Sharing Is Caring
  description: Easily share cards with other users, even if they don't have Catima installed.
  fontawesome_icon_name: share-alt

- title: Multilingual
  description: Available in more than 40 <a href="https://hosted.weblate.org/engage/catima/">community-contributed</a> languages.
  fontawesome_icon_name: globe

- title: Own Your Data
  description: Export your data with just a single press of a button.
  fontawesome_icon_name: file-export

links:
  - title: Chat
    url: https://matrix.to/#/%23catima:matrix.org

# Theme Settings
topbar_color: '#000000'
topbar_transparency: 0.1
topbar_title_color: '#ffffff'

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: '#363b3d'
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: '#ffffff'

link_color: '#1d63ea'

app_title_color: '#ffffff'
app_price_color: '#ffffff'
app_description_color: '#ffffff'

feature_title_color: '#000000'
feature_text_color: '#666666'

feature_icons_foreground_color: '#1d63ea'
feature_icons_background_color: '#e6e6e6'

social_icons_foreground_color: '#666666'
social_icons_background_color: '#e6e6e6'

footer_text_color: '#666666'

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
- LICENSE
- README.md
- CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

# .well-known
include:
  - ".well-known"
